# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuestionnaireDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QuestionnaireDemo

  target 'QuestionnaireDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuestionnaireDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end


pod 'MJExtension','~>3.0.13'
end
